-- Template D — Jackpot-Wheel bonuses (PLAYERBONUS_ES_RECOVERY_REPORT.md §5.4)
-- CHUNK KEY: JWB.CREATEDDATE
SELECT
    JWB.USERBONUSID,
    JWB.BONUSID,
    JWB.USERID,
    JWB.CREATEDDATE,
    JWB.STATUSID,
    JWB.CURRENCYID,
    JWB.MENU_ITEM_ID,
    JWB.AMOUNTWON,
    JWB.BONUSCODE,
    JWB.PRIZEID,
    JWPD.PRIZETYPE,                                   -- JackpotWheelSegmentType id (1=FREE_SPINS, 2=CASH_BONUS, ...)
    JWPD.FREESPINS            AS PRIZE_FREESPINS,    -- prize template free spins (used by twisterPrizeWon for FREE_SPINS)
    JWB.TRIGGERING_TRANSACTIONID,
    JWB.TRIGGERING_CAUSE,
    JWB.CREATEDDATE + B.EXPIERY_DAYS AS EXPIRATIONDATE,
    B.BONUSNAME,
    B.ACTIVEDAYS,
    B.EXPIERY_DAYS,
    B.DESCRIPTION,
    B.SPECIALBONUSTYPEID,
    CUR.CURRENCY              AS CURRENCY_ISO,      -- GAMER.CURRENCIES.CURRENCY (ISO code)
    /* --- user (split across USERDETAILS2 + CASINO.USERS + IR_SYS_USERACCOUNTS) --- */
    UD.EXTERNALUSERID,                                -- GAMER.USERDETAILS2.EXTERNALUSERID
    UD.USER_PARENT_ID,
    UA.INTERNALACCOUNT        AS INTERNAL_ACCOUNT,   -- GAMER.IR_SYS_USERACCOUNTS.INTERNALACCOUNT
    UP.EXTERNAL_PARENT_ID     AS EXTERNAL_PARENT_USERID,  -- GAMER.USER_PARENT.EXTERNAL_PARENT_ID
    CU.SKINID,                                        -- CASINO.USERS.SKINID
    /* --- skin (SKINS carries SKIN/SKINORIGIN; GROUPID via junction) --- */
    SK.SKIN                   AS SKIN_NAME,         -- GAMER.SKINS.SKIN (skin keyword)
    SK.SKINORIGIN             AS SKIN_ORIGIN_ID,     -- GAMER.SKINS.SKINORIGIN
    SGS.GROUPID               AS SKIN_GROUP_ID       -- GAMER.SKINGROUPSKINS.GROUPID
FROM GAMER.JACKPOT_WHEEL_BONUSES JWB
JOIN GAMER.BONUSES        B   ON JWB.BONUSID     = B.BONUSID
JOIN GAMER.CURRENCIES     CUR ON CUR.CURRENCYID  = JWB.CURRENCYID
LEFT JOIN GAMER.JACKPOT_WHEEL_PRIZES_DESC JWPD ON JWPD.PRIZEID = JWB.PRIZEID
JOIN GAMER.USERDETAILS2           UD  ON UD.USERID          = JWB.USERID
JOIN CASINO.USERS                 CU  ON CU.USERID          = JWB.USERID
LEFT JOIN GAMER.IR_SYS_USERACCOUNTS UA ON UA.USERID          = JWB.USERID
LEFT JOIN GAMER.USER_PARENT       UP  ON UP.USER_PARENT_ID  = UD.USER_PARENT_ID
JOIN GAMER.SKINS                  SK  ON SK.SKINID          = CU.SKINID
LEFT JOIN GAMER.SKINGROUPSKINS    SGS ON SGS.SKINID         = CU.SKINID
WHERE JWB.CREATEDDATE >= TO_DATE(:from_ts, 'YYYY-MM-DD HH24:MI:SS')
  AND JWB.CREATEDDATE <  TO_DATE(:to_ts,   'YYYY-MM-DD HH24:MI:SS')
