-- @range
SELECT
    MIN(U.USERID) AS MIN_ID,
    MAX(U.USERID) AS MAX_ID
FROM GAMER.USERS2 U
LEFT OUTER JOIN GAMER.USERDETAILS2 UD ON UD.USERID = U.USERID
LEFT OUTER JOIN GAMER.SALARY_RANGES SR ON SR.ID    = UD.SALARY_RANGE_ID
WHERE SR.FROM_SALARY IS NOT NULL
  AND SR.TO_SALARY   IS NOT NULL

-- @batch
SELECT
    U.USERID                                                AS "userId",
    TO_CHAR(SR.FROM_SALARY) || '-' || TO_CHAR(SR.TO_SALARY) AS "salary"
FROM GAMER.USERS2 U
LEFT OUTER JOIN GAMER.USERDETAILS2 UD ON UD.USERID = U.USERID
LEFT OUTER JOIN GAMER.SALARY_RANGES SR ON SR.ID    = UD.SALARY_RANGE_ID
WHERE SR.FROM_SALARY IS NOT NULL
  AND SR.TO_SALARY   IS NOT NULL
  AND U.USERID >= :from_id
  AND U.USERID <  :to_id
ORDER BY U.USERID
