MODE: id_range_union
PK: id
BANCH_VALUE: 5000
INDEX_NAME: cardusers
ES_ENV: prod
parts:
  - sql_file: sql/regular.sql
    VALUE_COLM: mapping/regular.csv
    ID_COLUMN: CCN.CARDID
  - sql_file: sql/applepay.sql
    VALUE_COLM: mapping/applepay.csv
    ID_COLUMN: AP.DPAN_ID
