-- Template C — Wheel-Spin bonuses (PLAYERBONUS_ES_RECOVERY_REPORT.md §5.3)
-- CHUNK KEY: WS.CREATEDDATE
SELECT
    WS.USERID,
    WS.BONUSWHEELSPINID,
    WS.BONUSID,
    WS.DENOMINATION,
    WS.LINES,
    WS.COINS,
    WS.MULTIPLIER,
    WS.WHEELSPINSTATUSID,
    WS.CREATEDDATE,
    WS.MENUITEMSIDS,
    WS.BONUSCODE,
    WS.TRIGGERING_TRANSACTIONID,
    WS.TRIGGERING_CAUSE,
    WS.PRIZEWON,                         -- confirmed column (scratchtemp/src/com/EUC/bonus/BonusDAO.java:144)
    B.BONUSNAME,
    B.ACTIVEDAYS,
    B.EXPIERY_DAYS,
    B.DESCRIPTION,
    B.SPECIALBONUSTYPEID,
    CUR.CURRENCY              AS CURRENCY_ISO,      -- GAMER.CURRENCIES.CURRENCY (ISO code)
    /* --- user (split across USERDETAILS2 + CASINO.USERS + IR_SYS_USERACCOUNTS) --- */
    UD.EXTERNALUSERID,                                -- GAMER.USERDETAILS2.EXTERNALUSERID
    UD.USER_PARENT_ID,
    UA.INTERNALACCOUNT        AS INTERNAL_ACCOUNT,   -- GAMER.IR_SYS_USERACCOUNTS.INTERNALACCOUNT
    UP.EXTERNAL_PARENT_ID     AS EXTERNAL_PARENT_USERID,  -- GAMER.USER_PARENT.EXTERNAL_PARENT_ID
    CU.SKINID,                                        -- CASINO.USERS.SKINID
    /* --- skin (SKINS carries SKIN/SKINORIGIN; GROUPID via junction) --- */
    SK.SKIN                   AS SKIN_NAME,         -- GAMER.SKINS.SKIN (skin keyword)
    SK.SKINORIGIN             AS SKIN_ORIGIN_ID,     -- GAMER.SKINS.SKINORIGIN
    SGS.GROUPID               AS SKIN_GROUP_ID       -- GAMER.SKINGROUPSKINS.GROUPID
FROM GAMER.WHEELSPIN_BONUSES WS
JOIN GAMER.BONUSES        B   ON WS.BONUSID      = B.BONUSID
JOIN GAMER.CURRENCIES     CUR ON CUR.CURRENCYID  = WS.CURRENCYID
JOIN GAMER.USERDETAILS2           UD  ON UD.USERID          = WS.USERID
JOIN CASINO.USERS                 CU  ON CU.USERID          = WS.USERID
LEFT JOIN GAMER.IR_SYS_USERACCOUNTS UA ON UA.USERID          = WS.USERID
LEFT JOIN GAMER.USER_PARENT       UP  ON UP.USER_PARENT_ID  = UD.USER_PARENT_ID
JOIN GAMER.SKINS                  SK  ON SK.SKINID          = CU.SKINID
LEFT JOIN GAMER.SKINGROUPSKINS    SGS ON SGS.SKINID         = CU.SKINID
WHERE WS.CREATEDDATE >= TO_DATE(:from_ts, 'YYYY-MM-DD HH24:MI:SS')
  AND WS.CREATEDDATE <  TO_DATE(:to_ts,   'YYYY-MM-DD HH24:MI:SS')
