-- Template B — Free-Spins / Free-Chips bonuses (PLAYERBONUS_ES_RECOVERY_REPORT.md §5.2)
-- CHUNK KEY: FS.CREATEDATE  (column spelled 'CREATEDATE' on this table)
SELECT
    FS.USERID,
    FS.FREEBONUSID,
    FS.BONUSID,
    FS.FREESPINS,
    FS.FREESPINS_LEFT,
    FS.DENOMINATION,
    FS.LINES,
    FS.COINS,
    FS.MULTIPLIER,
    FS.MAXWIN,
    FS.AMOUNT_WON,
    FS.FREESPINS_STATUSID,
    FS.SESSIONID,
    FS.CREATEDATE             AS CREATEDDATE,
    CAST(FS.MENUITEMIDS AS VARCHAR2(4000)) AS MENUITEMIDS,
    CAST(FS.PROMOCODE   AS VARCHAR2(200))  AS FSPROMOCODE,
    FS.TRIGGERING_TRANSACTIONID,
    FS.TRIGGERING_CAUSE,
    B.BONUSNAME,
    B.ACTIVEDAYS,
    B.EXPIERY_DAYS,
    B.DESCRIPTION,
    B.SPECIALBONUSTYPEID,
    CUR.CURRENCY              AS CURRENCY_ISO,      -- GAMER.CURRENCIES.CURRENCY (ISO code)
    /* --- user (split across USERDETAILS2 + CASINO.USERS + IR_SYS_USERACCOUNTS) --- */
    UD.EXTERNALUSERID,                                -- GAMER.USERDETAILS2.EXTERNALUSERID
    UD.USER_PARENT_ID,
    UA.INTERNALACCOUNT        AS INTERNAL_ACCOUNT,   -- GAMER.IR_SYS_USERACCOUNTS.INTERNALACCOUNT
    UP.EXTERNAL_PARENT_ID     AS EXTERNAL_PARENT_USERID,  -- GAMER.USER_PARENT.EXTERNAL_PARENT_ID
    CU.SKINID,                                        -- CASINO.USERS.SKINID
    /* --- skin (SKINS carries SKIN/SKINORIGIN; GROUPID via junction) --- */
    SK.SKIN                   AS SKIN_NAME,         -- GAMER.SKINS.SKIN (skin keyword)
    SK.SKINORIGIN             AS SKIN_ORIGIN_ID,     -- GAMER.SKINS.SKINORIGIN
    SGS.GROUPID               AS SKIN_GROUP_ID       -- GAMER.SKINGROUPSKINS.GROUPID
FROM GAMER.FREESPINS_BONUSES FS
JOIN GAMER.BONUSES        B   ON FS.BONUSID      = B.BONUSID
JOIN GAMER.CURRENCIES     CUR ON CUR.CURRENCYID  = FS.CURRENCYID
JOIN GAMER.USERDETAILS2           UD  ON UD.USERID          = FS.USERID
JOIN CASINO.USERS                 CU  ON CU.USERID          = FS.USERID
LEFT JOIN GAMER.IR_SYS_USERACCOUNTS UA ON UA.USERID          = FS.USERID
LEFT JOIN GAMER.USER_PARENT       UP  ON UP.USER_PARENT_ID  = UD.USER_PARENT_ID
JOIN GAMER.SKINS                  SK  ON SK.SKINID          = CU.SKINID
LEFT JOIN GAMER.SKINGROUPSKINS    SGS ON SGS.SKINID         = CU.SKINID
WHERE FS.CREATEDATE >= TO_DATE(:from_ts, 'YYYY-MM-DD HH24:MI:SS')
  AND FS.CREATEDATE <  TO_DATE(:to_ts,   'YYYY-MM-DD HH24:MI:SS')
