SELECT
    CCN.CARDID,
    MIN(CCU.CREATIONDATE) AS CREATIONDATE,
    CCN.HIDDEN_CARD_NUMBER,
    CCN.EXPYEAR,
    CCN.EXPMONTH,
    CCN.BLACKLIST,
    CV.VERIFIED,
    CAST(CCO.COMPANYNAME AS VARCHAR2(200)) AS COMPANYNAME,
    CAST(BST.STATUS      AS VARCHAR2(200)) AS STATUS,
    LISTAGG(CAST(U.EXTERNALUSERID AS VARCHAR2(100)), ',')
        WITHIN GROUP (ORDER BY U.EXTERNALUSERID) AS EXTERNALUSERIDS,
    LISTAGG(U.USERID, ',')
        WITHIN GROUP (ORDER BY U.USERID) AS USERIDS
FROM GAMER.CREDITCARDNUMBERS CCN
LEFT JOIN GAMER.CREDITCARDS_USERS CCU
    ON CCU.CARDID = CCN.CARDID
LEFT JOIN GAMER.USERDETAILS2 U
    ON U.USERID = CCU.USERID
LEFT JOIN GAMER.IR_SYS_CREDITCARDCOMPANIES CCO
    ON CCN.CARDTYPE = CCO.CREDITCARDCOMPANYID
LEFT JOIN GAMER.CREDITCARDS_VERIFIED CV
    ON CV.CARDID = CCN.CARDID
LEFT JOIN GAMER.CREDITCARDBINS BIN
    ON BIN.BINID = CCN.BINID
LEFT JOIN GAMER.CREDITCARDBINSTATUSES BST
    ON BST.STATUSID = BIN.STATUS
--WHERE CCU.CREATIONDATE >= TO_DATE(:from_ts, 'YYYY-MM-DD HH24:MI:SS')
--  AND CCU.CREATIONDATE <  TO_DATE(:to_ts,   'YYYY-MM-DD HH24:MI:SS')
GROUP BY
    CCN.CARDID,
    CCN.HIDDEN_CARD_NUMBER,
    CCN.EXPYEAR,
    CCN.EXPMONTH,
    CCN.BLACKLIST,
    CV.VERIFIED,
    CCO.COMPANYNAME,
    BST.STATUS
