-- @range
SELECT
    MIN(CCN.CARDID) AS MIN_ID,
    MAX(CCN.CARDID) AS MAX_ID
FROM GAMER.CREDITCARDNUMBERS CCN

-- @batch
SELECT
    'REGULAR' || TO_CHAR(CCN.CARDID)                            AS "id",
    CCN.CARDID                                                  AS CARDID,
    MIN(CCU.CREATIONDATE)                                       AS CREATIONDATE,
    CCN.HIDDEN_CARD_NUMBER                                      AS HIDDEN_CARD_NUMBER,
    CCN.EXPYEAR                                                 AS EXPYEAR,
    CCN.EXPMONTH                                                AS EXPMONTH,
    CCN.BLACKLIST                                               AS BLACKLIST,
    CV.VERIFIED                                                 AS VERIFIED,
    CAST(CCO.COMPANYNAME AS VARCHAR2(200))                      AS COMPANYNAME,
    CAST(BST.STATUS      AS VARCHAR2(200))                      AS STATUS,
    LISTAGG(CAST(U.EXTERNALUSERID AS VARCHAR2(100)), ',')
        WITHIN GROUP (ORDER BY U.EXTERNALUSERID)                AS EXTERNALUSERIDS,
    LISTAGG(U.USERID, ',')
        WITHIN GROUP (ORDER BY U.USERID)                        AS USERIDS
FROM GAMER.CREDITCARDNUMBERS CCN
LEFT JOIN GAMER.CREDITCARDS_USERS CCU
    ON CCU.CARDID = CCN.CARDID
LEFT JOIN GAMER.USERDETAILS2 U
    ON U.USERID = CCU.USERID
LEFT JOIN GAMER.IR_SYS_CREDITCARDCOMPANIES CCO
    ON CCN.CARDTYPE = CCO.CREDITCARDCOMPANYID
LEFT JOIN GAMER.CREDITCARDS_VERIFIED CV
    ON CV.CARDID = CCN.CARDID
LEFT JOIN GAMER.CREDITCARDBINS BIN
    ON BIN.BINID = CCN.BINID
LEFT JOIN GAMER.CREDITCARDBINSTATUSES BST
    ON BST.STATUSID = BIN.STATUS
WHERE CCN.CARDID >= :from_id
  AND CCN.CARDID <  :to_id
GROUP BY
    CCN.CARDID,
    CCN.HIDDEN_CARD_NUMBER,
    CCN.EXPYEAR,
    CCN.EXPMONTH,
    CCN.BLACKLIST,
    CV.VERIFIED,
    CCO.COMPANYNAME,
    BST.STATUS
ORDER BY CCN.CARDID
