-- Template A — Redeem-Eligible bonuses (PLAYERBONUS_ES_RECOVERY_REPORT.md §5.1)
-- CHUNK KEY: ISU.CREATEDDATE
SELECT
    /* --- fact: IR_SYS_USERSBONUSES --- */
    ISU.USERBONUSID,
    ISU.USERID,
    ISU.BONUSID,
    ISU.AMOUNT,
    ISU.AMOUNTLEFT,
    ISU.STATUSID,
    BS.STATUSNAME,
    ISU.CREATEDDATE,
    ISU.EXPIRATIONDATE,
    ISU.POINTSTOREDEEM        AS REDEEMPOINTS,
    CAST(ISU.PROMOCODE AS VARCHAR2(200)) AS PROMOCODE,
    ISU.TRIGGERING_TRANSACTIONID,
    ISU.TRIGGERING_CAUSE,
    /* --- per-row expiry days override (Java reads ISU.EXPIERY_DAYS via UserBonusRowMapper:30) --- */
    ISU.EXPIERY_DAYS                  AS EXPIERY_DAYS,
    /* --- template: BONUSES --- */
    B.BONUSNAME,
    B.ACTIVEDAYS,
    B.DESCRIPTION,
    B.SPECIALBONUSTYPEID,
    /* --- currency --- */
    CUR.CURRENCY              AS CURRENCY_ISO,   -- ISO code, e.g. "USD" (Currency.java:32-34)
    /* --- user --- */
    UD.EXTERNALUSERID,
    UD.USER_PARENT_ID,
    UA.INTERNALACCOUNT        AS INTERNAL_ACCOUNT,        -- GAMER.IR_SYS_USERACCOUNTS.INTERNALACCOUNT
    UP.EXTERNAL_PARENT_ID     AS EXTERNAL_PARENT_USERID,  -- GAMER.USER_PARENT.EXTERNAL_PARENT_ID
    /* --- skin: ids + name; SkinGroup/SkinOrigin names resolved in Python --- */
    SK.SKINID,
    SK.SKIN                   AS SKIN_NAME,         -- GAMER.SKINS.SKIN (skin keyword)
    SK.SKINORIGIN             AS SKIN_ORIGIN_ID,     -- GAMER.SKINS.SKINORIGIN
    SGS.GROUPID               AS SKIN_GROUP_ID        -- GAMER.SKINGROUPSKINS.GROUPID
FROM GAMER.IR_SYS_USERSBONUSES ISU
JOIN GAMER.BONUSES                B   ON ISU.BONUSID        = B.BONUSID
JOIN GAMER.BONUSSTATUSES          BS  ON ISU.STATUSID       = BS.STATUSID
JOIN GAMER.CURRENCIES             CUR ON CUR.CURRENCYID     = ISU.CURRENCYID
JOIN GAMER.USERDETAILS2           UD  ON UD.USERID          = ISU.USERID
JOIN CASINO.USERS                 CU  ON CU.USERID          = ISU.USERID    -- SKINID lives here
LEFT JOIN GAMER.IR_SYS_USERACCOUNTS UA ON UA.USERID          = ISU.USERID   -- INTERNALACCOUNT
LEFT JOIN GAMER.USER_PARENT       UP  ON UP.USER_PARENT_ID  = UD.USER_PARENT_ID  -- EXTERNAL_PARENT_ID
JOIN GAMER.SKINS                  SK  ON SK.SKINID          = CU.SKINID
LEFT JOIN GAMER.SKINGROUPSKINS    SGS ON SGS.SKINID         = CU.SKINID     -- N:M (see §9 #11)
WHERE ISU.CREATEDDATE >= TO_DATE(:from_ts, 'YYYY-MM-DD HH24:MI:SS')
  AND ISU.CREATEDDATE <  TO_DATE(:to_ts,   'YYYY-MM-DD HH24:MI:SS')
